ImperialCollegeLondon/paricia

measurement/models.py

Close #114 
Adds the base model that will be used by all measurement-related models. It will replace, ultimately, the existing `BaseMeasurement` class and `create_meas_model` function. 
As it is an abstract model that do not add an entry to the DB and , there's nothing to test (at least [not without a lot of work](https://stackoverflow.com/questions/4281670/django-best-way-to-unit-test-an-abstract-model)). Tests will be added down the line, after benchmarking has proved that this is performant enough.

Add MeasurementBase model

---

measurement/models.py
tests/measurement/test_models.py

Add completeness and time validation to Report

---

validated/dash_apps/finished_apps/daily_validation.py
validated/plots.py
validated/tables.py

This PR makes some cosmetic changes to the plot, and includes a radio selector to choose whether to display minimum, maximum or average data

Improvements to the plot

---

validated/dash_apps/finished_apps/daily_validation.py

This adds a date picker to the bar at the bottom of the tables which can be used to choose a date for the detail view, rather than the numerical input that was used before.
I've also moved the bar outside of the tabs so now a single bar is shared between between both tables, with logic added to the callback to change the behaviour of the buttons depending on which tab is selected.

Use date picker to specify date for detail table

---

requirements.txt
static/styles/dashstyle.css
validated/dash_apps/finished_apps/daily_validation.py
validated/functions.py
validated/plots.py
validated/tables.py

Creates a dash app to visualise data in tabular and graph form, and manually save to the Validated dataset. Replicates the original Daily Validation Javascript app (http://localhost:8000/validated/daily_validation/). 
The new app is a self-contained page accessible at http://localhost:8000/validated/daily_validation_dev/
For now, the data filters are specified in the code, although eventually we will want to include these as drop downs on the page (either through the existing django forms or new dash objects).
---
I'm keeping this as a master branch for #121, and merging PRs into this branch as I add new features.
PRs already merged:
#143 Making a start on the tables, showing the appropriate data, conditional styling
#145 Callbacks for adding new data and saving to validated
#151 …

Daily validation dash app

---

.gitignore
README.md
requirements-dev.txt
utilities/benchmarking/create_synthetic_data_scenario1.py
utilities/benchmarking/create_synthetic_data_scenario2.py

Adds the scripts to create synthetic data in two scenarios, ~ 24M entries spread over 23 years and the same entries compressed in just 1 year. 
A Wiki summarising the findings is included here: https://github.com/ImperialCollegeLondon/paricia/wiki/Performance-benchmarking

Add synthetic data creation scenarios

---

utilities/benchmarking/benchmark_queries.py

This PR adds the script to benchmark the performance of making queries with the new single `Measurement` model. Conditions for using this script are the same than for the synthetic data, already included in the README in another PR.
A summary of the findings can be found in the [wiki](https://github.com/ImperialCollegeLondon/paricia/wiki/Performance-benchmarking#query-results).

Add script for benchmarking queries

---

.github/workflows/ci.yml

Publishes Paricia in the GitHub package registry as a docker container, so it can be deployed anywhere else easily. 
When we're ready to go to production, this should run only when there's a new release. For now, during development, this will run anytime we make a push to the `develop` branch to allow for quickly testing changes.
Contributes to #142

Publish Paricia as a docker container

---

measurement/validation.py
tests/measurement/test_validation.py

Launches the calculation of the reports when saving the validated data, either when saving days or when saving individual entries. It also deletes reports data in the relevant time range when resetting validation.
Fixes #208

Launch reports when saving or resetting validation

---

measurement/validation.py

To avoid flagging entries on the basis of negligible differences, a +-2% tolerance has been added to the timelapse comparison.

Make timelapse labelling more flexible

---

management/admin.py

This limits the list of users when creating an object so that a user can only select themselves as the owner of an object they are creating. Currently there is also an option of selecting no owner, as object ownership is not compulsory, however I plan to address this in #221 
Close #220

Limit object ownership to active user

---

management/admin.py
measurement/admin.py

This fixes some bugs in the admin classes which should allow superusers to add and change objects without problems.
- previously permissions were being checked by checking object ownership rather than the actual permissions attributes, which obviously won't work for superusers
- there were issues before if any objects didn't have an owner. Long term we will make object ownership mandatory, but until then this should fix those problems
There will still be issues with add permissions for non-superusers.

Fix bugs in admin classes

---

management/admin.py
management/models.py
measurement/admin.py
measurement/apps.py
measurement/models.py
measurement/signals/handlers.py
sensor/signals/handlers.py
station/models.py
station/signals/handlers.py
tests/permissions/test_permissions.py
variable/signals/handlers.py

This makes a number of changes to the permissions system, with the goal of fixing any problems for standard users.
- Apply the model level `add` permission to the standard user group for all models. This is achieved through a `post_migrate` signal. Previously, standard users were able to add objects due to the `has_add_permission` method in the admin class, but the models didn't appear in the admin homepage. This change fixes this and also allows the `has_add_permission` method to check the permissions directly.
- Use the `get_queryset` method in the admin class, which limits the objects that are visible based on view permissions. Without this, all objects would be visible even to standard users.
- Remove the `save_model` method from the admin class. This just checks that the user has …

Make admin work for standard users

---

management/admin.py
station/admin.py

This ensures that standard users can only create private objects through the admin page. Superusers can still create public objects. The reason is to ensure that all public objects are vetted and maintained by admins, and aren't irresponsibly changed or deleted
The exception is stations, which still maintain the three options (private, public and internal) for all users. Here, the permissions level is a bit different as it relates to visibility of measurements, and all registered users should be allowed to create public measurements.
Close #202

Restrict permissions level of objects created through admin

---

importing/views.py

This adds a check to the DataImportFullCreate view to make sure the user has permissions for the station they're uploading measurements for
Close #206

Check station permissions in importing app

---

validated/dash_apps/finished_apps/daily_validation.py
validated/dash_apps/finished_apps/data_report.py
validated/filters.py

This repeats the process carried out in #219 #242 and #243 to automatically populate the filters in the data report app based on the data. Since there's a lot of shared code between the data report and validation apps, I have moved most of the code to `filters.py` (which currently contains a lot of other stuff that needs to be deleted) 
I have also removed the `clear_form` callback, as this was causing clashes with my other callbacks, and isn't really needed anyway

Callbacks to populate filters in report page

---

utilities/load_initial_data.py

`Delta_T` initial data should be loaded before `Station`, as the later contains references to the former.

:bug: Load initial data in the right order

---

CONTRIBUTING.md

Basically emojis within a text bloc are rendered as images, so they need to be in list in order to be considered just emojis. Not sure if that is the expected behaviour, but it is not a big dela in this case and it works. 
Close #354

Fix odd behavior of emojis in guidelines

---

management/views.py

For some reason, conditionally setting the owner was not working correctly - at least not for the `data_import` model, even though the model has an `owner` field. This way we are forcing the ownership unconditionally. As all models using these forms have owner, it should work.

Fix owner not being set correctly

---

measurement/validation.py
tests/measurement/test_validation.py

The lines were commented due to a past refactor and we forgot to uncomment them.
Close #385

Fix daily count in validation

---

measurement/validation.py
tests/measurement/test_validation.py

The report calculation needs the data to be validated, so what it is done is that if anything fails during the report calculation, the validation is reset. This is done for both the full day validation and the individual entries validation.
Close #383

Reset validation if reporting fails

---

formatting/views.py
management/views.py
templates/object_detail.html

Add the classifications (i.e. the variables and the column they can be found) to the format detail view. Links are included to the classification object, the variable and the unit, so they can be explored further. 
Things have been setup in a general form, such that they can be added to any detail view, should that be needed. 
Close #407

Add inline classifications to format
